INSERT INTO [Citizens] ([Name],[Email],[Phone], [CitizenTypeId])
	VALUES ('José Antonio Moura','joseantonio@moura.com','+55 34 989811711', 2)
INSERT INTO [Citizens] ([Name],[Email],[Phone], [CitizenTypeId]) 
	VALUES ('Monica Lessa Ribeiro','monicaribeiro@ribeiro.com','+55 34 39811711', 2)
INSERT INTO [Citizens] ([Name],[Email],[Phone], [CitizenTypeId]) 
	VALUES ('Armazén Dia', 'diaarmazen@armazen.com','+55 34 999822231', 1)
INSERT INTO [Citizens] ([Name],[Email],[Phone], [CitizenTypeId])
	VALUES ('I Investimentos', 'iinvestimentos@iinvestimentos.com','+55 34 33811722', 1)
INSERT INTO [Citizens] ([Name],[Email],[Phone], [CitizenTypeId])
	VALUES ('Fazenda Campo Belo','campobelo@fazendacampobelo.com','+55 34 38281713', 3)
INSERT INTO [Citizens] ([Name],[Email],[Phone], [CitizenTypeId])
	VALUES ('Fazendinha','fazendinha@fazendinha.com','+55 34 33287011', 3)