INSERT INTO [Citizens] ([Name],[Password],[Email],[Phone], [CitizenTypeId])
	VALUES ('José Antonio Moura','poccitizens01','joseantonio@moura.com','+55 34 989811711', 2)
INSERT INTO [Citizens] ([Name],[Password],[Email],[Phone], [CitizenTypeId]) 
	VALUES ('Monica Lessa Ribeiro','poccitizens02','monicaribeiro@ribeiro.com','+55 34 39811711', 2)
INSERT INTO [Citizens] ([Name],[Password],[Email],[Phone], [CitizenTypeId]) 
	VALUES ('Armazén Dia','poccitizens03', 'diaarmazen@armazen.com','+55 34 999822231', 1)
INSERT INTO [Citizens] ([Name],[Password],[Email],[Phone], [CitizenTypeId])
	VALUES ('I Investimentos','poccitizens04', 'iinvestimentos@iinvestimentos.com','+55 34 33811722', 1)
INSERT INTO [Citizens] ([Name],[Password],[Email],[Phone], [CitizenTypeId])
	VALUES ('Fazenda Campo Belo','poccitizens05','campobelo@fazendacampobelo.com','+55 34 38281713', 3)
INSERT INTO [Citizens] ([Name],[Password],[Email],[Phone], [CitizenTypeId])
	VALUES ('Fazendinha','poccitizens06','fazendinha@fazendinha.com','+55 34 33287011', 3)